#pragma once

#include <string>
#include <unordered_map>
#include <vector>
#include <iostream>
#include <stdexcept>
#include "exceptionhelper.h"
#include <memory>

//JAVA TO C++ CONVERTER NOTE: Forward class declarations:
namespace org { namespace eclipse { namespace keyple { namespace seproxy { namespace exception { class KeypleBaseException; } } } } }

/********************************************************************************
 * Copyright (c) 2018 Calypso Networks Association https://www.calypsonet-asso.org/
 *
 * See the NOTICE file(s) distributed with this work for additional information regarding copyright
 * ownership.
 *
 * This program and the accompanying materials are made available under the terms of the Eclipse
 * Public License 2.0 which is available at http://www.eclipse.org/legal/epl-2.0
 *
 * SPDX-License-Identifier: EPL-2.0
 ********************************************************************************/
namespace org {
    namespace eclipse {
        namespace keyple {
            namespace example {
                namespace generic_Renamed {
                    namespace pc {

                        using KeypleBaseException = org::eclipse::keyple::seproxy::exception::KeypleBaseException;

                        /**
                         * This class handles the reader events generated by the SeProxyService
                         */
                        class Demo_SeProtocolDetection_Pcsc : public std::enable_shared_from_this<Demo_SeProtocolDetection_Pcsc> {

                        public:
//JAVA TO C++ CONVERTER TODO TASK: No base class can be determined:
                            Demo_SeProtocolDetection_Pcsc(); //super();

                            /**
                             * Application entry
                             *
                             * @param args the program arguments
                             * @throws IllegalArgumentException in case of a bad argument
                             * @throws KeypleBaseException if a reader error occurs
                             */
                            static void main(std::vector<std::string> &args) throw(std::invalid_argument, KeypleBaseException);
                        };

                    }
                }
            }
        }
    }
}
